dist: xenial
language: node_js
cache: yarn

node_js:
  - '8'
  - '10'
  - '11'

before_install:
  # Use newer yarn than that pre-installed in the Travis image.
  - curl -sSfL https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - |
    yarn --frozen-lockfile
    yarn forever start node_modules/verdaccio/build/lib/cli.js --config verdaccio.yml
    yarn lerna publish from-package preminor --registry http://localhost:4873 --no-git-reset --yes --git-head $TRAVIS_COMMIT

script:
  - yarn validate:eslintrc
  - yarn lint
  - yarn prettier:check
  - yarn test
  - yarn ava --verbose packages/create-project/test

after_script:
  - rm -rf "$(yarn cache dir)"/*-neutrino-*/ "$(yarn cache dir)"/*-@neutrinojs/
