image: Visual Studio 2017
build: off
shallow_clone: true
matrix:
  fast_finish: true

environment:
  SKIP_CHANGELOG: true
  YARN_AUTH_TOKEN: '//localhost:4873/:_authToken=token'
  matrix:
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - |
    choco install yarn
    yarn --frozen-lockfile
    yarn forever start node_modules/verdaccio/build/lib/cli.js --config verdaccio.yml
    yarn lerna publish from-package preminor --registry http://localhost:4873 --no-git-reset --yes --git-head %APPVEYOR_REPO_COMMIT%

test_script:
  - yarn validate:eslintrc
  - yarn lint
  - yarn prettier:check
  - yarn test
  - yarn ava --verbose packages/create-project/test

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
