image: Visual Studio 2017
build: off
shallow_clone: true
matrix:
  fast_finish: true

environment:
  matrix:
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '8'

install:
  - git --version
  - ps: Install-Product node $env:nodejs_version
  - |
    choco install yarn
    yarn --frozen-lockfile
    node node_modules/forever/bin/forever start node_modules/verdaccio/build/lib/cli.js --config verdaccio.yml
    node node_modules/lerna/cli.js publish from-package preminor --registry http://localhost:4873 --no-git-reset --yes --git-head %APPVEYOR_REPO_COMMIT%

test_script:
  - yarn validate:eslintrc
  - yarn lint
  - yarn prettier:check
  - yarn test
  - node scripts/test-create-project-ci.js

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
